config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/posts' => 'posts#index'
  get '/posts/new' => 'posts#new', as: :new_post
  get '/posts/:id' => 'posts#show', as: :post
  post '/posts' => 'posts#create'
  get '/posts/:id/edit' => 'posts#edit'
  patch '/posts/:id' => 'posts#update'
  delete '/posts/:id' => 'posts#destroy', as: :destroy_post

  post '/posts/:post_id/comments' => 'comments#create', as: :post_comments

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments

   has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])

    comment_body = params[:comment][:body]

    post.comments.create body: comment_body

    respond_to do |format|
      format.json { head :no_content }
      format.html { redirect_to post_path(post) }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 3)

    respond_to do |format|
      format.html
      format.json { render text: @posts.to_json }
    end
  end

  def create
    post = Post.create post_params

    flash[:notice] = "Successfully created post"

    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])

    title = params[:post][:title]
    body = params[:post][:body]

    post.title = title
    post.body = body

    post.save

    flash[:notice] = "Updated  post"

    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy

    flash[:notice] = "Deleted post"

    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  private

  def post_params
    params[:post].permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def formatted_date(post)
    post.created_at.strftime('%e %b %Y')
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">TalentSpace</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li><%= current_user.email %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>

        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_post.html.erb
 <div class="post">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="post-title">
        <% if params[:action] == 'show' %>
          <%= post.title %>
        <% else %>
          <%= link_to post.title, post_path(post) %>
        <% end %>
      </h1>
      <div class="meta-data">
        <p><%= formatted_date(post) %></p>
        <%= link_to 'delete', destroy_post_path(post), method: :delete %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p>
        <%= post.body %>
      </p>
      <%= image_tag post.image.url(:medium) %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <br/>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/posts/index.html.erb
<% if flash[:notice]  %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>

<% @posts.each do |post| %>
  <%= render partial: 'post', locals: { post: post } %>
  <hr />
<% end %>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true }  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: 'Hello World!' %>

  <br/>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.file_field :image %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/posts/show.html.erb
<% if flash[:notice]  %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>
<%= render partial: 'post', locals: { post: @post } %>

<hr />

<h2>Comments</h2>

<%= form_for @comment, url: post_comments_path(@post) do |f| %>
  <%= f.text_area :body, style: 'width: 100%' %>
  <br />
  <%= f.submit 'Submit' %>
<% end %>

<br />

<div class='comments'>
  <% @post.comments.order('created_at desc').each do |comment| %>
    <p><%= comment.body %></p>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>